export const ScreenNames = {
    HOME: 'Home',
    PROGRESS: 'Progress',
    FORUM: 'Forum',
    RANKING: 'Ranking',
    SETTINGS: 'Settings',
    ADD_PROGRESS: 'AddProgress',
    ADD_GOAL: 'Add a Monthly Goal',
    BROWSER: 'Browser',
    QUIZ: 'Quiz',
    LOGIN: 'Login',
    SIGNUP: 'Signup',
    RECORD_EMISSION: 'Track Your Emissions',
    FOOD: 'Diet',
    RECYCLING: 'Recycling',
    TRANSPORTATION: 'Transportation',
    ELECTRICITY: 'Electricity Usage',
    QUESTIONNAIRE: "Questionnaire",
    PREDICT: "Predict Emissions",
    CALCULATION_DETAILS: "Calculation Details",
};