export const ScreenNames = {
    HOME: 'Home',
    PROGRESS: 'Progress',
    FORUM: 'Forum',
    RANKING: 'Ranking',
    SETTINGS: 'Settings',
    ADD_PROGRESS: 'AddProgress',
    ADD_GOAL: 'AddGoal',
    BROWSER: 'Browser',
    QUIZ: 'Quiz',
    LOGIN: 'Login',
    SIGNUP: 'Signup',
    RECORD_EMISSION: 'Track your Emissions',
    FOOD: 'Food',
    RECYCLING: 'Recycling',
    TRANSPORTATION: 'Transportation',
};